# Generated by Django 5.2.17 on 2026-09-25 21:31

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único identificador (ej: CHOC-001)', max_length=50, unique=True, verbose_name='Código del Producto')),
                ('nombre', models.CharField(help_text='Nombre comercial del producto', max_length=150, verbose_name='Nombre del Chocolate')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles del chocolate, notas de cata o ingredientes', null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('Negro / Amargo', 'Negro / Amargo (70%+ Cacao)'), ('Con Leche', 'Chocolate con Leche'), ('Blanco', 'Chocolate Blanco'), ('Relleno / Bombón', 'Bombones y Rellenos'), ('Trufas', 'Trufas Artesanales'), ('Edición Especial', 'Edición Especial / Gourmet')], default='Negro / Amargo', max_length=50, verbose_name='Categoría')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio unitario en Bolivianos', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Precio (Bs.)')),
                ('cantidad_existente', models.PositiveIntegerField(default=0, help_text='Unidades físicas disponibles', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Stock')),
                ('estado', models.BooleanField(default=True, help_text='Indica si el producto está disponible para la venta', verbose_name='Estado Activo')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que ingresó al inventario', verbose_name='Fecha de Ingreso')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Fotografía del Producto')),
                ('porcentaje_cacao', models.PositiveIntegerField(blank=True, default=70, help_text='Porcentaje de pureza de cacao (0 a 100)', null=True, verbose_name='% de Cacao')),
                ('origen_cacao', models.CharField(blank=True, default='Alto Beni, Bolivia', max_length=100, verbose_name='Origen del Cacao')),
            ],
            options={
                'verbose_name': 'Producto de Chocolatería',
                'verbose_name_plural': 'Productos de Chocolatería',
                'ordering': ['-fecha_ingreso', 'nombre'],
            },
        ),
    ]
